openapi: 3.0.0
info:
  title: Recommendation API V2
  version: "2.0"
servers:
  - url: https://api.neynar.com/v2

components:
  schemas:
    Address:
      $ref: "../spec.yaml#/components/schemas/Address"
    User:
      $ref: "../spec.yaml#/components/schemas/User"
    ErrorRes:
      $ref: "../spec.yaml#/components/schemas/ErrorRes"
    RelevantMint:
      type: object
      description: A mint object relevant to the user
      required:
        - contract_address
        - token_id
        - block_number
        - tx_hash
        - minter
      properties:
        contract_address:
          $ref: "#/components/schemas/Address"
        token_id:
          type: string
        block_number:
          type: integer
          format: int32
        tx_hash:
          type: string
        minter:
          $ref: "#/components/schemas/User"
    RelevantMints:
      type: object
      description: A list of mint objects relevant to the user
      required:
        - mints
      properties:
        mints:
          type: array
          items:
            $ref: "#/components/schemas/RelevantMint"

  parameters:
    ApiKey:
      name: api_key
      in: header
      required: true
      schema:
        type: string
        default: NEYNAR_API_DOCS
      description: API key required for authentication.

  responses:
    ServerErrorResponse:
      description: "Server Error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorRes"
    RelevantMintsResponse:
      description: "Relevant Mints Response"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RelevantMints"

tags:
  - name: NFT
    description: NFT Recommendations API
    externalDocs:
      description: NFT Recommendations API
      url: https://docs.neynar.com/reference/

paths:
  /nft/relevant_mints:
    get:
      tags:
        - NFT
      summary:  Relevant Mints for a User
      description: Fetches all mint actions relevant for a contract address (and optionally tokenId for ERC1155s) given a user's ethereum address
      operationId: fetch-relevant-mints
      parameters:
        - $ref: '#/components/parameters/ApiKey'
        - name: address
          required: true
          in: query
          example: "0x5a927ac639636e534b678e81768ca19e2c6280b7"
          schema:
            $ref: "#/components/schemas/Address"
        - name: contract_address
          required: true
          in: query
          example: "0xe8e0e543a3dd32d366cb756fa4d112f30172bcb1"
          schema:
            $ref: "#/components/schemas/Address"
        - name: token_id
          required: false
          in: query
          example: "1"
          schema:
            type: string
      responses:
        "200":
          $ref: "#/components/responses/RelevantMintsResponse"
        "500":
          $ref: "#/components/responses/ServerErrorResponse"
