openapi: 3.0.0
info:
  title: STP API V2
  version: "2.0"
servers:
  - url: https://api.neynar.com/v2

components:
  schemas:
    ConflictErrorRes:
      type: object
      required:
        - message
      description: Details for the conflict error response
      properties:
        code:
          type: string
        message:
          type: string
        property:
          type: string
        key:
          type: string
    ErrorRes:
      type: object
      required:
        - message
      description: Details for the error response
      properties:
        code:
          type: string
        message:
          type: string
        property:
          type: string
        status:
          type: integer
          format: int32
    SubscriptionCheckResponse:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/SubscriptionStatus'
      example:
        "0xedd3783e8c7c52b80cfbd026a63c207edc9cbee7":
          object: "subscribed_to_dehydrated"
          status: true
          expires_at: 1748890497000
          subscribed_at: 1719256819704
          tier:
            id: 1
            price:
              period_duration_seconds: 2592000
              tokens_per_period: "3499999997472000"
              initial_mint_price: "0"
        "0x5a927ac639636e534b678e81768ca19e2c6280b7":
          object: "subscribed_to_dehydrated"
          status: false
          expires_at: null
          subscribed_at: null
          tier: null 
    SubscriptionStatus:
      type: object
      properties:
        object:
          type: string
          enum: ["subscribed_to_dehydrated"]
        status:
          type: boolean
        expires_at:
          type: integer
          format: int64
          nullable: true
        subscribed_at:
          type: integer
          format: int64
          nullable: true
        tier:
          $ref: '#/components/schemas/SubscriptionTier'
          nullable: true
      required:
        - object
        - status
        - expires_at
        - subscribed_at
        - tier
    SubscriptionTier:
      type: object
      properties:
        id:
          type: integer
          example: 1
        price:
          type: object
          properties:
            period_duration_seconds:
              type: integer
              example: 2592000
            tokens_per_period:
              type: string
              example: "3000000000000000"
            initial_mint_price:
              type: string
              example: "0"

  parameters:
    ApiKey:
      name: api_key
      in: header
      required: true
      schema:
        type: string
        default: NEYNAR_API_DOCS
      description: API key required for authentication.

  responses:
    401Response:
      description: "Unauthorized"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorRes"
    404Response:
      description: "Resource not found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorRes"
    400Response:
      description: "Bad Request"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorRes"
    403Response:
      description: "Forbidden"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorRes"
    409Response:
      description: "Conflict"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ConflictErrorRes"
    500Response:
      description: "Server Error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorRes"



paths:
  /stp/subscription_check:
    get:
      tags:
        - STP
      summary: Check if a user is subscribed to a STP contract
      description: Check if a user is subscribed to a given STP contract.
      operationId: subscription-check
      externalDocs:
        url: https://docs.neynar.com/reference/subscription-check
      parameters:
        - $ref: "#/components/parameters/ApiKey"
        - name: addresses
          description: Comma separated list of Ethereum addresses, up to 350 at a time
          in: query
          required: true
          example: 0xedd3783e8c7c52b80cfbd026a63c207edc9cbee7,0x5a927ac639636e534b678e81768ca19e2c6280b7
          schema:
            type: string
        - name: contract_address
          description: Ethereum address of the STP contract
          in: query
          required: true
          example: "0x76ad4cb9ac51c09f4d9c2cadcea75c9fa9074e5b"
          schema:
            type: string
        - name: chain_id
          description: Chain ID of the STP contract
          in: query
          required: true
          example: "8453"
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionCheckResponse"
        "400":
          $ref: "#/components/responses/400Response"