name: Create Pull Request in Rust SDK

on:
  push:
    # branches:
    #   - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OAS repository
        uses: actions/checkout@v3

      - name: Checkout rust-sdk repository
        uses: actions/checkout@v3
        with:
          repository: "neynarxyz/rust-sdk.git"
          ref: "main"
          path: "rust-sdk"
          token: ${{ secrets.OAS_TO_SDK_FGPAT }}
          submodules: recursive
          persist-credentials: true

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Update OAS submodule and package version in rust-sdk
        run: |
          # Get the author of the prior commit
          AUTHOR=$(git log -1 --pretty=format:'%ae')
          cd rust-sdk

          # Update OAS submodule
          git submodule update --remote src/OAS

          # Set Git config
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Parse version from OAS
          # Install yq for YAML parsing
          sudo wget -O /usr/bin/yq https://github.com/mikefarah/yq/releases/download/v4.24.5/yq_linux_amd64
          sudo chmod +x /usr/bin/yq
          SDK_VERSION=$(yq e '.info."version"' src/OAS/src/v2/spec.yaml)
          echo "SDK Version: $SDK_VERSION"

          # Check if SDK_VERSION is empty
          if [ -z "$SDK_VERSION" ]; then
            echo "Error: version not found in OAS file."
            exit 1
          fi

          # Set branch name using SDK_VERSION and GITHUB_RUN_ID
          BRANCH_NAME="update-oas-v${SDK_VERSION}-${GITHUB_RUN_ID}"
          echo "Branch Name: $BRANCH_NAME"

          # Export variables for use in subsequent steps
          echo "SDK_VERSION=$SDK_VERSION" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV

          # Create and checkout the new branch
          git checkout -b "$BRANCH_NAME"

          # Commit updated OAS submodule
          git add .
          git commit -m "Update OAS submodule"

          # Generate code
          #./generate.sh

          # Commit generated files
          git add .
          git commit -m "Update generated files"

        shell: bash

      - name: Create Pull Request via API
        run: |
          # Install jq for JSON parsing
          sudo apt-get update && sudo apt-get install -y jq

          # Prepare JSON payload for the pull request
          DATA=$(jq -n \
            --arg title "Update OAS submodule to version $SDK_VERSION" \
            --arg head "$BRANCH_NAME" \
            --arg base "main" \
            --arg body "This pull request updates the OAS submodule to include the latest changes." \
            '{title: $title, head: $head, base: $base, body: $body}')

          echo "Creating Pull Request with data: $DATA"

          # Create the pull request via GitHub API
          RESPONSE=$(curl -X POST \
          -H "Authorization: token ${{ secrets.OAS_TO_SDK_FGPAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/neynarxyz/rust-sdk/pulls \
          -d "$DATA")

          # Extract the pull request number from the response
          PR_NUMBER=$(echo "$RESPONSE" | jq -r '.number')
          echo "Pull Request Number: $PR_NUMBER"

          # Check if PR_NUMBER is valid
          if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" == "null" ]; then
          echo "Error: Failed to create pull request."
          echo "Response: $RESPONSE"
          exit 1
          fi

          # Prepare JSON payload for the review request
          REVIEWERS=$(jq -n --arg reviewer "$AUTHOR" '[ $reviewer ]')
          REVIEW_REQUEST_DATA=$(jq -n \
          --argjson reviewers "$REVIEWERS" \
          '{reviewers: $reviewers}')

          echo "Creating Review Request with data: $REVIEW_REQUEST_DATA"

          # Create the review request via GitHub API
          curl -X POST \
          -H "Authorization: token ${{ secrets.OAS_TO_SDK_FGPAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/neynarxyz/rust-sdk/pulls/$PR_NUMBER/requested_reviewers \
          -d "$REVIEW_REQUEST_DATA"
        shell: bash
